# Generated by Django 5.0.13 on 2025-11-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.TextField(blank=True, null=True)),
                ('temperatura_ideal', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_almacenamiento', models.CharField(blank=True, max_length=50, null=True)),
                ('es_peligroso', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('turno', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('licencia_manejo_montacargas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('contacto_persona', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('condiciones_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo_entrega_dias', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_sku', models.CharField(max_length=50, unique=True)),
                ('stock_actual', models.IntegerField(default=0)),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volumen_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ultimo_movimiento', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_BodegaAlmacen.categoriaalmacen')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_BodegaAlmacen.proveedoralmacen')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inventario', models.DateField(blank=True, null=True)),
                ('stock_sistema', models.IntegerField(default=0)),
                ('stock_fisico', models.IntegerField(default=0)),
                ('diferencia', models.IntegerField(default=0)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('empleado_realizo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_BodegaAlmacen.empleadoalmacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_BodegaAlmacen.productoalmacen')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entrada', models.IntegerField(default=0)),
                ('fecha_entrada', models.DateTimeField(blank=True, null=True)),
                ('num_factura_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_BodegaAlmacen.empleadoalmacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_BodegaAlmacen.productoalmacen')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_BodegaAlmacen.proveedoralmacen')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_salida', models.IntegerField(default=0)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('id_cliente_salida', models.IntegerField(blank=True, null=True)),
                ('num_pedido_salida', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_salida', models.TextField(blank=True, null=True)),
                ('empleado_despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_BodegaAlmacen.empleadoalmacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_BodegaAlmacen.productoalmacen')),
            ],
        ),
    ]
